version: '3.8'

services:
  app:
    build: .
    ports:
      - "8086:8086"
    depends_on:
      - db
      - user-service
      - order-service
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=2005b
      - DB_NAME=cinema_db
      - DB_PORT=5432
      - USER_SERVICE_URL=http://user-services:8081
      - ORDER_SERVICE_URL=http://order-services:8082


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2005b
      POSTGRES_DB: cinema_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  migrate:
#    image: migrate/migrate
#    depends_on:
#      - db
#    volumes:
#      - ./db/migrations:/migrations
#    entrypoint: ["/bin/sh", "-c"]
#    command: >
#      migrate -path=/migrations -database "postgres://postgres:2005b@db:5432/cinema_db?sslmode=disable" up

  user-service:
    build:
      context: ../user_service
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cinema_db
      - DB_USER=postgres
      - DB_PASSWORD=2005b

  order-service:
    build:
      context: ../order_service
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cinema_db
      - DB_USER=postgres
      - DB_PASSWORD=2005b

volumes:
  postgres_data:
